name: useless_db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  bson: ^5.0.3
  collection: ^1.18.0
  path: ^1.9.0
  synchronized: ^3.1.0+1
  uuid: ^4.3.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
